openapi: 3.0.0
info:
  title: Entro Finance API
  description: API simple de prueba para Mintlify
  version: 1.0.0
servers:
  - url: https://api.entro.finance

paths:
  /hello:
    get:
      tags:
        - Test
      summary: Saludo simple
      description: Endpoint de prueba que devuelve un saludo
      operationId: getHello
      responses:
        "200":
          description: Saludo exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hola desde Entro Finance API"
                  timestamp:
                    type: string
                    example: "2024-01-15T10:30:00Z"
